sudo: required
dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - wget -q https://codeload.github.com/glassechidna/zxing-cpp/tar.gz/master -O master.tar.gz
  - tar xzf master.tar.gz
  - cd zxing-cpp-master/
  - mkdir build/
  - cd build/
  - cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_CXX_FLAGS=-fPIC ..
  - make
  - sudo make install
  - cd ../..
  - make install
script:
  - make lint test
deploy:
  provider: pypi
  user:
    secure: lwgPAQQagNgeeo5jfQdUl3H0X2LXyxtbyiOdpGbQMl8W0UH/EUQnvw96RKUK9GKEzBUyT/dd205e3JQNZVoKPrwTydNhiepzIidoj2bT2/+sglUUtwKMqd5+P2c81rsSIQQJsuGFnhGl+cjBChq2LsWFEpg6RvfABP1CbFABju+xq7g5e9BsWEasSKMlMJMyfi7RaBhllBaF86Qu9Hfi9szuPR9zZJBjtX5g1AzNicEd2PiqvNiYI6t29/ESVsMCg/2pGXSq0QpaUE20DpxHX4xT8sxycbLSCQqrkpCHMnQsu/369VT0HUDF1XPon87pquNrRiZtxhQ+khV4pRW08dVBUmzl0oXNT8l86NSiz7dkmN5YHlzMhRABjYun0EqZ/0cj2zmSK/4xTXHojZFtPlNtrrsJG2Hxi1rEAP/A3VwmlJKLcTS3FER9uDHV6afRapT02/xZ1dbpGBpH+zdQV45XCgiHOK2K8VRHPP6Z4rCywuxo0e8Evbyaj0lRPRfqCbKObeSvslPURF+aXqCcZOdTZdQWWs9xKapMMjrnbjuKoVX0KtfQVndbQ1WeBrSPOBQg3GCHzs2wUFSQA37UuqjFc5nyQEbm5vtOKqYG8ON1rz39A11wvTUrcuZ4wZ5FrJ+f8EFIQG8Y8VHZNx5FKWJIxQIOxDGkVvRLXit0QXw=
  password:
    secure: pArxFXfU1c8oQ2lkTqKzai2xel2aFz7kadD7mt8vYY8+6uyeIfBbDwjW3Asjce1BfjKEoAlqW/rDHrp1Hx8oQyr7IIhhvQTa5zogxtsCK70bI1DCAKBy2jxAWkSG9hkdJWFqkwVEGwfazPAyMt/Rp/ujVF6iNHsjTGlAH4lvaeYVejRG7RCakNqQkNYQsRwtjd3RNTI8XKlbNefjmxAwMn5CI+7gJMMkHnRORo0evkjA1JiONsXC/8Y2e/2Y/bAjmj8lke1pqzPWW6TSPxRItvEgWz2ntB5y5iu/0FECgh0WDAV6rGoHoOmO/WIGdgFy5fAkv73UPy+BH+lPUzBrjRMRLXba/R238Am0r4BY6Iw5wTWY8+Nfl2tZOBJ1EaKH5Iv3mnqhubC3pTMvGKVnfOlqOxYF3X0sZEdhb8TZVzlOLyHrd+IMdltqWcTSZ17XYLCUgr4u1oiepiXwvQtSMmk1divaDr5eKi6uM9Gz5LQOagrJyp6E29b7UeatPBFt42sDZlIZuhDiw09G+AWWVymiH3+dhGXKGYAfMp5GaMGCAyzJAD0WaSHdpGxS8f0wCnjfYBjsIgm+uOz8x2CLM+6Gpqg8mGzGGDey0RCxvnflN2Wuddb3LR3R+NPuFiSidVVfqE8WZd02B9+PhyxY5Thm5ilUCUf8qOo69fLv1gA=
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = '3.7'"
